# Generated by Django 5.1.4 on 2024-12-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_alter_coins_symbol_alter_wallets_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coins",
            name="min_exchange_settlement",
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name="wallets",
            name="owner",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name="wallet",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Settlements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("external_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="markets.coins"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transactions",
            name="settlement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="markets.settlements",
            ),
        ),
    ]
