# Generated by Django 5.1.4 on 2024-12-12 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_coins_min_exchange_settlement_alter_wallets_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coins",
            name="min_exchange_settlement",
            field=models.FloatField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="coins",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="coins",
            name="symbol",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2,10}$", message="Invalid symbol"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settlements",
            name="amount",
            field=models.FloatField(
                editable=False, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="settlements",
            name="coin",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="markets.coins",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="coin",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="markets.coins",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="price",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
