# Generated by Django 5.1.4 on 2024-12-12 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_alter_coins_min_exchange_settlement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coins",
            name="min_exchange_settlement",
        ),
        migrations.AlterField(
            model_name="coins",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0001)]
            ),
        ),
    ]
