services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mini_exchange
      - POSTGRES_USER=mini_exchange
      - POSTGRES_PASSWORD=complex_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mini_exchange" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-bookworm
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  celery-worker:
    build: .
    command: celery -A mini_exchange worker -l info
    environment:
      - MINI_EXCHANGE__POSTGRES_NAME=mini_exchange
      - MINI_EXCHANGE__POSTGRES_USER=mini_exchange
      - MINI_EXCHANGE__POSTGRES_PASSWORD=complex_password
      - MINI_EXCHANGE__POSTGRES_HOST=db
      - MINI_EXCHANGE__REDIS_HOST=redis
    depends_on:
      - db
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MINI_EXCHANGE__POSTGRES_NAME=mini_exchange
      - MINI_EXCHANGE__POSTGRES_USER=mini_exchange
      - MINI_EXCHANGE__POSTGRES_PASSWORD=complex_password
      - MINI_EXCHANGE__POSTGRES_HOST=db
      - MINI_EXCHANGE__REDIS_HOST=redis
    depends_on:
      - db
      - redis
